### PR TITLE
10 data volume

### PR DESCRIPTION
**Pull request by chilland**
Haven't had a chance to test this yet, so consider it a WIP for now.

### CODE REVIEW

**Comment by chilland** [comment]
Tested and debugged

**Comment by ahalterman** [comment]
Woo! Awesome work. I'm reviewing now. Quick question: the documentation in the new "Basic Usage" section is stuff most users won't need to mess with, right? Just people who need to change the defaults, right?

**Comment by chilland** [comment]
Right. I admittedly skimped on the documentation. Basically the way it works now should support running it the same was as before, but the configs can now also be changed via command line or environment variable. This allows you to change them while running in a container, as well as also working without Docker entirely (modulo dependencies).

**Comment by ahalterman** [comment]
:+1: Everything runs fine and looks good here. I'll make a separate PR with some documentation changes. Thanks!

**Pull request merged**
